### ISSUE TITLE
Media Element: Move fields under Media tab to general tab.

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/fluidcontent_core#122]
Hi there, 

I just want to know your opinion about this. General tab in Media CE is too empty, I suggest to move content from Media tab to General tab as enchacement.

Regards.

**Comment by NamelessCoder** [comment]
Makes sense from a usability standpoint if your editors experience almost empty tabs. However, this would be a redefinition of the strategy that's used by the core and as such, I wouldn't include it in this extension (but of course, feel free to suggest that change to the TYPO3 core bug tracker - I know for a fact that work is being done to get rid of CSC's fields which means soon, the core will face the same tab composition that's used in FCC).

You can as always override this TCA yourself. Simply override the `showItems` entry, for example in your provider extension's `ext_tables.php` file. If needed, consult the (very old) TCA documentation for how to construct the `showItems` value - it uses a fairly cryptic syntax from a decade or so back.
