### ISSUE TITLE
[BUG] Headlines not working

### ISSUE THREAD

**Issue by randomresult** [FluidTYPO3/fluidcontent_core#124]
When inserting an FCE or a plugin (indexedsearch) and entering an Headline this headline does not show up in frontend. 
Works for "normal" Contentelements.

Typo3 6.2.9 (latest git) 
FCC latest master and development. (github)
Let me know if you need further informations.

**Comment by NamelessCoder** [comment]
To render headers it is required to have the header in the Layout of the template(s) that are rendered. Is is possible that indexedsearch either depends on CSC and doesn't use Fluid, or that you did not override/overlay the layoutRootPath to change the Layout used by indexedsearch so it either uses the shared Layout or a copy of it?

**Comment by NamelessCoder** [comment]
Hi @randomresult - did the answer solve your problem? If it did, please close this one. If not, a gist of your template, the layout and the TS it uses might reveal a bit more.

**Comment by NamelessCoder** [comment]
I'm taking the liberty of closing this one and assuming you solved the issue.

**Comment by konstantin83** [comment]
Actually, headlines not showed at all. CSC renders them perfectly, but i use fluidcontent_core only. What code should I include in my provider extension with my own custom content element template to render headlines and it's layout (selected H tag and a css class)?
