### ISSUE TITLE
Wrong PHPDoc return

### ISSUE THREAD

**Issue by xf-** [FluidTYPO3/fluidcontent_core#125]
https://github.com/FluidTYPO3/fluidcontent_core/blob/development/Classes/Provider/CoreContentProvider.php#L343
returns something and not void

**Comment by cedricziel** [comment]
Nope. Fields are passed by reference and processed. Parent returns void as well (https://github.com/FluidTYPO3/flux/blob/development/Classes/Provider/AbstractProvider.php)

**Comment by NamelessCoder** [comment]
I believe strict standards would warn about this. Here in PHPstorm I get a warning if *any* return statement is found in a method that declares `@return void`.
