### ISSUE TITLE
Menu is not working

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/fluidcontent_core#132]
TYPO3 Version 7.0.3
Expected:
Get menuPartialTemplateName populated in FE request with SubPagesOfSelectedPages
Output:
#1225709597: The template files "/home/vagrant/www/jmverges.dev/typo3conf/ext/fluidcontent_core/Resources/Private/Partials/Menu/", "/home/vagrant/www/jmverges.dev/typo3conf/ext/fluidcontent_core/Resources/Private/Partials/Menu/.html" could not be loaded. (More information)

AdditionalConfiguration.php:
$additionalConfiguration = array(
		'FE/activateContentAdapter' => FALSE,
		'FE/contentRenderingTemplates' => array('fluidcontentcore/Configuration/TypoScript/')
);
\TYPO3\CMS\Core\Configuration\ConfigurationManager::setLocalConfigurationValuesByPathValuePairs($additionalConfiguration);

Admin works fine and is rendering properly SubPagesOfSelectedPages
<f:render partial="Properties/Menu/{menuPartialTemplateName}" arguments="{_all}" />

**Comment by Madii** [comment]
Well this works for me in Typo3 7.1

**Comment by jmverges** [comment]
I tried Menu again with 6.2 LTS. All is working as expected except Related Pages (based on keywords) that is returning to me 

'Tried to get a variable "sections" which is not stored in the context!'

or 

Fatal error: Call to undefined method FluidCache_FluidcontentCore_CoreContent_partial_Menu_RelatedPages_8f66fe677a1b75f2896aa0322cb9c5d491ba370e::section_62bce9422ff2d14f69ab80a154510232fc8a9afd() in /var/www/typo3_src/typo3/sysext/fluid/Classes/View/AbstractTemplateView.php on line 222 

a bit randomly. Can anyone confirm this issue?

**Comment by xf-** [comment]
62bce9422ff2d14f69ab80a154510232fc8a9afd is the sha1 hash for Main.
The relatedPages partial is empty and PHP trows a error because of the missing Main section.

**Comment by xf-** [comment]
Should close #35
