### ISSUE TITLE
Argument key was not registered

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/fluidcontent_core#137]
I'm not sure if this is a fluidcontent_core issue or vhs issue.
TYPO3 version: 7.1
FluidTYPO3 stack version: development
Each time that I try to include some fluidcontent_core element, I'm getting: 
![typo3 exception](https://cloud.githubusercontent.com/assets/2902073/6501187/9dc184f8-c315-11e4-92fc-883ee2dd4fcc.png)
http://pastebin.com/dDvpN7kb

**Comment by NamelessCoder** [comment]
Fixed; https://github.com/FluidTYPO3/vhs/pull/779
