### ISSUE TITLE
After Update to current TER versions, I got error messages ...

### ISSUE THREAD

**Issue by matt-rein** [FluidTYPO3/fluidcontent_core#144]
... if I used variants and /or versions.

Uncaught TYPO3 Exception
#1: PHP Warning: strpos() expects parameter 1 to be string, array given in /kunden/135359_61348/baukasten/typo3conf/ext/flux/Classes/Utility/ExtensionNamingUtility.php line 27

**Comment by typo3ua** [comment]
I have all collapsed and after the update all has stopped working.
I am using - Concept: Overlaying and Overriding
