### ISSUE TITLE
Problem with partialRootPaths and variants

### ISSUE THREAD

**Issue by matt-rein** [FluidTYPO3/fluidcontent_core#151]
I have the following typoscript:
##
plugin.tx_fluidcontentcore {
    view {
        templateRootPaths.1 = EXT:mrebaukasten/Resources/Private/Templates/
        partialRootPaths.1 = EXT:mrebaukasten/Resources/Private/Partials/CoreContent/
        layoutRootPaths.1 = EXT:mrebaukasten/Resources/Private/Layouts/CoreContent/
    }
}
##

If I select a variant I got the following error message:
##
#1225709597: The template files "/kunden/135359_61348/baukasten/typo3conf/ext/mrebaukasten/Resources/Private/Partials/Properties/Images.html", "/kunden/135359_61348/baukasten/typo3conf/ext/mrebaukasten/Resources/Private/Partials/Properties/Images" could not be loaded.
##

This is a part of the affected fluid template:
##
f:section name="Configuration">
	flux:form id="image">
		f:render partial="Properties/Images" arguments="{_all}" />
		f:render partial="Properties/Header" arguments="{_all}" />
		f:render partial="Properties/Container" arguments="{_all}" />
		f:if condition="{settings.extendedCaptions}">
.....
##
		
If I change one of the partial to an unknown one (Properties/Images2) the following error message appears. This one is okay because this partial file is not available.
##
#1225709597: The template files "/kunden/135359_61348/baukasten/typo3conf/ext/mrebaukasten/Resources/Private/Partials/CoreContent/Properties/Images2.html", "/kunden/135359_61348/baukasten/typo3conf/ext/mrebaukasten/Resources/Private/Partials/CoreContent/Properties/Images2", "/kunden/135359_61348/baukasten/typo3conf/ext/fluidcontent_core/Resources/Private/Partials/Properties/Images2.html", "/kunden/135359_61348/baukasten/typo3conf/ext/fluidcontent_core/Resources/Private/Partials/Properties/Images2" could not be loaded. (More information)  		
##

Why? I the first case it should also search on both 'partialRootPaths'. Or do I a misstak.

**Comment by typo3ua** [comment]
I have the same problem.
~~~
plugin.tx_fluidcontentcore {
	view {
		templateRootPaths >
		templateRootPaths {
			0 = {$plugin.tx_fluidcontentcore.view.templateRootPaths.default}
			1 = EXT:my/Resources/Private/Templates/Extensions/FluidContentCore/Templates/
		}
		partialRootPaths >
		partialRootPaths {
			0 = {$plugin.tx_fluidcontentcore.view.partialRootPaths.default}
			1 = EXT:my/Resources/Private/Templates/Extensions/FluidContentCore/Partials/
		}
		layoutRootPaths >
		layoutRootPaths {
			0 = {$plugin.tx_fluidcontentcore.view.layoutRootPaths.default}
			1 = EXT:my/Resources/Private/Templates/Extensions/FluidContentCore/Layouts/
		}
	}
}
~~~
and so ...
~~~
plugin.tx_fluidcontentcore {
	view {
		overlays {
			my {
				templateRootPaths.0 = EXT:my/Resources/Private/Templates/Extensions/FluidContentCore/Templates/
				partialRootPaths.0 = EXT:my/Resources/Private/Templates/Extensions/FluidContentCore/Partials/
				layoutRootPaths.0 = EXT:my/Resources/Private/Templates/Extensions/FluidContentCore/Layouts/
			}
		}
	}
}
~~~
The first and second options do not work. Why? What have I done wrong?

**Comment by glucka** [comment]
same Problem :(

**Comment by glucka** [comment]
```
plugin.tx_fluidcontentcore {
    view {
        templateRootPaths.100 = EXT:yourext/Resources/Private/ContentCore/Templates/
        partialRootPaths.100 = EXT:yourext/Resources/Private/ContentCore/Partials/
        layoutRootPaths.100 = EXT:yourext/Resources/Private/ContentCore/Layouts/
    }
}
```
write in the template setup record works
under myext/Configuration/setup.ts do not work

**Comment by mithri** [comment]
Nothing worked for me. How can i make variants with the partials from fluidcontent_core. Maybe this is a bug in the core?

**Comment by mithri** [comment]
Any news on this topic?

**Comment by NamelessCoder** [comment]
Under review - https://github.com/FluidTYPO3/flux/pull/840. In summary, caused by the use of "10" as default.

@glucka The paths must be set for your extension, not `fluidcontent_core`, e.g. `plugin.tx_yourext.view.*`.
