### ISSUE TITLE
Content element "Media" empty..., nothing on output.

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/fluidcontent_core#153]
I'm added content element "Media" on the page. Entered the necessary data in the form. I go to the page.... the page is empty. Why? What, I do wrong?

**Comment by NamelessCoder** [comment]
Currently not implemented - see https://github.com/FluidTYPO3/fluidcontent_core/issues/35. We would be very happy to receive pull requests to add this element's template!
