### ISSUE TITLE
Images in the backend - pages

### ISSUE THREAD

**Issue by Leopard99** [FluidTYPO3/fluidcontent_core#154]
Using an image-object in t3 6.2.9 (img or textimg) calling this error by trying to edit the page via backend->pages
Fatal error: Call to a member function getFileReferences() on a non-object in (...)/typo3_src-6.2.9/typo3/sysext/core/Classes/Resource/Service/FrontendContentAdapterService.php on line 90

**Comment by NamelessCoder** [comment]
Looks like a TYPO3 core specific issue. FluidcontentCore doesn't involve this method - you can work around it I think by disabling the "content adapter" setting in install tool, but you probably should report this one to the TYPO3 core bug tracker if this is still a problem on 6.2.12!
