### ISSUE TITLE
problem inserting record

### ISSUE THREAD

**Issue by braguzz** [FluidTYPO3/fluidcontent_core#160]
Updating to:
T3 6.2.11
flux	7.2.0	       	stable
fluidpages	3.2.0	       	stable
fluidcontent	4.2.1	     	stable
fluidcontent_core	1.1.2	     	beta
FBT: Bootstrap based Pages and Content	fluidbootstraptheme	1.1.0

I have some problems in add content element of type 'insert records'.

I can insert the record, but in FE nothing is renders.
activating debug I have this kind of errors:

```
ERROR	Unknown column 'tt_content_1435' in 'where clause'
lastBuiltQuery	SELECT * FROM tt_content WHERE uid IN (tt_content_1435) GROUP BY uid ORDER BY sorting ASC
```

if I insert css_styled_content page is rendered with the record.

arghhh

**Comment by bjo3rnf** [comment]
See #103

**Comment by cedricziel** [comment]
I have a fix to push today
