### ISSUE TITLE
elements disappear in page view when copied/dragged

### ISSUE THREAD

**Issue by SilkeDX** [FluidTYPO3/fluidcontent_core#162]
Hi,
I don't know if this is a bug or misconfiguration. I use latest TER versions (flux 7.2.0, fluidpages 3.2.2, fluidcontent 4.2.1).

When I copy an element and insert it into an FCE it disappears (normal cols just work fine). I tried to find out what went wrong (because I can see the elements in list view). When copying or dragging an element into FCE the colpos is 1 (instead of 18181) - or just isn't updated to 18181 when dragging - and tx_flux_col (from my two col FCE) is empty, tx_flux_parent is set to 0 instead of uid of parent FCE.

Copying and dragging worked fine before updating fluidtypo to newest versions. I had to do a few adjustments (like new namespaces) to get the new versions to work.

**Comment by SilkeDX** [comment]
I did go back to the previous versions (flux 7.1.2, fluidpages 3.1.2, fluidcontent 4.1.1) and everything works fine again.

**Comment by jenses** [comment]
I can't paste any elements into a FCE, but dragging and "paste after" (context menu) is working fine.
flux 7.2.0, fluidpages 3.2.2, fluidcontent 4.2.1

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/FluidTYPO3/flux/commit/bab7ca679c48230654c31f625ab06e3352ecb59c, will be in Flux 7.2.1.

**Comment by jenses** [comment]
Great! Works just fine as expected, again.
