### ISSUE TITLE
Shortcut don't work after update

### ISSUE THREAD

**Issue by mischka** [FluidTYPO3/fluidcontent_core#164]
After the update to 6.2.12 and fluidcontent_core 1.1.3 the shortcut-elements don't work anymore.
I got the following error;

```
   lastBuiltQuery	SELECT * FROM tt_content WHERE uid IN () GROUP BY uid ORDER BY sorting ASC
```
 I think the fix #161 is responsible for this ( https://github.com/FluidTYPO3/fluidcontent_core/commit/4f77d7e472b60a9b44849ba607cf29226352d01a ). In my $record-Array the records field only contains integer or lists of integer and no strings with prefix 'tt_content_':

    records => '89,149' (6 chars)

Which version of TYPO3 CMS introduced this string 'tt_content_' in shortcuts? 

In my case the contentUids are empty because there the records-field does not contain 'tt_content_'.

    array(2 items)
       0 => False

By replacing  ```return FALSE;``` with ```return $index;``` in the shortcutAction, everything works correctly.

    array(2 items)
       0 => '89' (2 chars)
       1 => '149' (3 chars)

**Comment by pkerling** [comment]
See #163

**Comment by NamelessCoder** [comment]
Under review in linked pull request - thanks @pkerling!
