### ISSUE TITLE
The typo3 form core extension does not work

### ISSUE THREAD

**Issue by FlorinPeter** [FluidTYPO3/fluidcontent_core#165]
I want to use the form typo3 core extension, after choosing the extension the are no configuration tabs. 

![form](https://cloud.githubusercontent.com/assets/2911849/8231261/980ef388-15c7-11e5-8f73-e49c6533a65f.png)

I get deeper in the code and found this line of code:
https://github.com/FluidTYPO3/fluidcontent_core/blob/development/Configuration/TCA/Overrides/tt_content.php#L256

after removing the line and clear the cache, it works.

![form2](https://cloud.githubusercontent.com/assets/2911849/8231359/3d8c8618-15c8-11e5-93f0-ce95ce49215a.png)

Is there an other fix or this a bug?

I use have the following extensions installed:

cdsrc_sass 1.1.0
fluidbootstraptheme 1.2.0
fluidcontent 4.2.2
fluidcontent_core 1.1.3
fluidpages 3.2.3
flux 7.2.1
realurl 1.13.3
vhs 2.3.3

**Comment by xf-** [comment]
@NamelessCoder should know more.
Never use that form stuff.

**Comment by NamelessCoder** [comment]
The coming version of TYPO3 separates these content types in to `css_styled_content` which is recorded as conflicting with `fluidcontent_core`. When that time comes around (and which was always the plan) you have two options:

* Use the TYPO3-provided, Fluid-based elements that *don't* depend on `css_styled_content`.
* Use any third-party plugin or fluidcontent template/controller that provides this feature.

The mailform and a few other types like the "media" type are no longer considered default core content types - we will be following that logic in `fluidcontent_core` so when the next TYPO3 LTS comes around, `fluidcontent_core` includes exactly the same CTypes as the TYPO3 core does *without* `css_styled_content` or other special content extensions installed.
