### ISSUE TITLE
Images are not accessible in new Variant of Image

### ISSUE THREAD

**Issue by Danny-P** [FluidTYPO3/fluidcontent_core#166]
Hi,
I've created a new Variant for Image in my template. 
Now I'd like to output these images, configured in the Backend. But I don't get access to them. 
In my template file I try: 
```
<v:resource.record.fal record="{record}" field="image" table="tt_content" as="images">
```
But "images" still remains empty. 
How can I get access to the images? The title is taken from {record.header}.

I'm Using Typo3 Version 7.1

Best regards
Daniel

**Comment by glucka** [comment]
I have maybe a similar problem. 
I do not see anymore the appearance tab by image element.

**Comment by jmverges** [comment]
Hi @Danny-P,
could you provide the full Variant?

**Comment by Danny-P** [comment]
Oh sorry. I didn't remind this issue. 
The problem has been solved. There was something in my coding wrong. Works now fine. 
Thank you!
