### ISSUE TITLE
Content Element Wizard broken

### ISSUE THREAD

**Issue by smichaelsen** [FluidTYPO3/fluidcontent_core#168]
This commit (https://github.com/TYPO3/TYPO3.CMS/commit/726d8647833c254394a72e26ac557021a14c8f12) moves functionality to css_styled_content which you want to have uninstalled when using `fluidcontent_core`.

Resulting in a broken new content element wizard: http://shots.michaelsen.io/IBF4

Anybody any idea how to tackle the problem?

**Comment by xf-** [comment]
A lot of TCA stuff was done in 7.4 and commit message says new rendering.
We noticed that problem, but 7.4 is under full development and currently with this many changes we can't support LTS and 7 release and git master. We would need a lot of updates and code for different versions.
We will fix this then somebody provides a PR or 7.4 is near release or released.
