### ISSUE TITLE
Text CE preview in BE works not right 

### ISSUE THREAD

**Issue by konstantin83** [FluidTYPO3/fluidcontent_core#174]
(see attached pic)

1. Create a new content element Text.
Add image in it. For example of the standard size (<= 300px).
Get back to the Page module, where CE is created. And you will see, that in content element list our new CE is rendered with a broken image tag.

2. If you increase max image width and height, and then make image in your Text CE bigger, for example 600px in width, and then come back to Page module, you will see a broken image tag with the dimensions of actual image element in CE.

This code in Text.html is responsible for rendering a preview:
`<f:section name="Preview">
{record.bodytext -> f:format.crop(maxCharacters: settings.preview.maxCharacters, append: '') -> v:or(alternative: row.bodytext)}
</f:section>
`

How do I fix this problem better?

![2015-07-30 15 52 19](https://cloud.githubusercontent.com/assets/13274062/8984493/a15931a4-36da-11e5-91df-6e53f9e32d06.png)
![2015-07-30 15 51 27](https://cloud.githubusercontent.com/assets/13274062/8984495/a15be52a-36da-11e5-80eb-5fb36ce6fd85.png)

**Comment by jmverges** [comment]
Hi @konstantin83,

I've never thought about this. I always thought and I'm still thinking using images into text is not the right way and only gives problems. This is something I always liked about TYPO3 by default this behaviour is not turned on.

By the way, is that editor the one provided by default? It looks like **TinyMCE** for me. 

Could be great if you can provide the **html generated in PreviewView** for your content.

Also could be great if you could confirm this wrong behaviour you are having is solved using any of the following combinations:

- fluidcontent_core +  HTMLArea 
- css_styled_content + TinyRTE
- css_styled_content + HTMLArea

Here we have to much things around and I would like to determine what is wrong. However this could be something we wouldn't like to support. Let us talk after you provide more information.

Regards

**Comment by xf-** [comment]
@jmverges +1

**Comment by konstantin83** [comment]
1. I switched to TinyMCE and back to HTMLAREA. It doesn't take effect.

These combinations:
css_styled_content + TinyRTE
css_styled_content + HTMLArea
are not possible as I use fluidcontent_core only and this exactly is it's content element called Text.

Here is the screenshot of what generates preview when image's width is 400px and it's floated left :)
![2015-07-31 0 14 08](https://cloud.githubusercontent.com/assets/13274062/8995324/5961084c-3719-11e5-9eab-62a37be8fe85.png)

And here is the code you asked for:
```HTML
<div class="t3-page-ce-body">
    <div class="t3-page-ce-body-inner">
        <div>
            <span class="exampleContent">
                <a name="c34"></a>
                <img src="fileadmin/_processed_/csm_thumbnail-full_2a1c57a485.jpg" width="400" height="278" data-htmlarea-file-uid="23" data-htmlarea-file-table="sys_file" title="" alt="" data-htmlarea-clickenlarge="1" style="float: left;">
                Some&nbsp;text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some text&nbsp;some
            </span>
        </div>
    </div>
</div>
```




2. Since we are discussing, could you please help with another thing? I can't manage how to output content element Header layout in my fluid content element?
I can output only header with this line:
`
<v:tag name="h{content.settings.header.type -> v:or(alternative: record.header_layout) -> v:or(alternative: settings.header.type)}" class="{content.settings.header.className}" hideIfEmpty="{content.settings.header.hideIfEmpty -> v:or(alternative: 1)}">
                    {record.header -> f:format.raw()}
                </v:tag>
`
But only because of record.header_layout is set to 0 (zero) as <f:debug> says.

Other words - how to get to these options in FLUID template:
![2015-07-31 0 27 33](https://cloud.githubusercontent.com/assets/13274062/8995581/0a1223a0-371b-11e5-9583-e15ff168fb5d.png)

**Comment by xf-** [comment]
you need to replace links to fileadmin because you are in typo3.
We do image handling via FAL, because this is hard to crop, you would load the original size.
i think most people disable images in RTE.

**Comment by jmverges** [comment]
@xf- +1 However @konstantin83 I would like to do some testing could you provide a gist with your RTE configuration?

**Comment by konstantin83** [comment]
I didn't do custom RTE configurations. So RTE is default. Installed only Typo3 6.2.14 and current version of fluidcontent_core (with it's dependencies)

**Comment by jmverges** [comment]
After testing the behaviour without fluidcontent_core I can conclude css_styled_content removes the images appended from the preview.

**Comment by konstantin83** [comment]
That's an easy solution, I did it instantly by changing the preview section in Text.html (fluidcontent_core)
from `f:format.crop` to `f:format.html`
`{record.bodytext -> f:format.html() -> v:or(alternative: row.bodytext)}`

If that is the only way to render preview, then let it be.

**Comment by jmverges** [comment]
We need to maintain the crop where it is. However you solution works fine.

**Comment by konstantin83** [comment]
Ok then.

**Comment by konstantin83** [comment]
What about the second question - about FLUID rendering of Header and it's selected layout?
I create a content element with FLUID, add it to page, then write content element's Header and choose for example H1 and a class of it (like always), but to render header in FE I need to include in in my content template html file. How is it possible?

**Comment by jmverges** [comment]
First of all, did you create fluidcontent_core element or a custom one based on fluidcontent? I'm not getting you.

**Comment by konstantin83** [comment]
I created extension with Builder and a custom html content template based on fluidcontent.

**Comment by jmverges** [comment]
could you provide the full html of your custom content?

**Comment by jmverges** [comment]
I think this is not place for this conversation, could you come to our support channel https://fluidtypo3.org/community/support-chat.html ?

**Comment by konstantin83** [comment]
Sure

```HTML
<div xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers" xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers" xmlns:f="http://typo3.org/ns/fluid/ViewHelpers">

    <f:layout name="Content" />

    <f:section name="Configuration">
        <f:render partial="Properties/Header" arguments="{_all}" />
        <f:render partial="Properties/Container" arguments="{_all}" />
        <flux:form id="gallery" wizardTab="QuadroCom" label="Гелерея">
            <flux:field.inline.fal name="settings.images" multiple="TRUE" maxItems="20" />

                <flux:grid>
                    <v:resource.record.fal record="{record}" field="image" table="tt_content" as="images">
                        <f:for each="{images}" as="image" iteration="iteration">
                            <flux:grid.row>
                                <flux:grid.column name="content{image.checksum}" label="{v:l(key: 'caption', arguments: '{0: image.name}')}" />
                            </flux:grid.row>
                        </f:for>
                    </v:resource.record.fal>
                </flux:grid>

        </flux:form>
    </f:section>

    <f:section name="Preview">
        <b><f:translate key="flux.gallery" /></b>
    </f:section>

    <f:section name="Resources">
    </f:section>

    <f:section name="Item">
        <div class="<f:if condition="{settings.images.className}">{settings.image.className -> v:format.replace(substring: ',', replacement: ' ')}<f:else> col-xs-6 col-sm-3 </f:else></f:if>">
            <a href="{image.url}" title="{f:if(condition: image.description, then: '{image.title}: ', else: '{image.title}')}{image.description}" rel="group{record.uid}" class="fancybox gallery-item">
                <f:image treatIdAsReference="TRUE" src="{image.id}" alt="{image.title}" title="{f:if(condition: image.description, then: '{image.title}: ', else: '{image.title}')}{image.description}" width="170c" height="170c" />
            </a>
        </div>
    </f:section>

    <f:section name="Main">
        <f:debug>{header}</f:debug>
        <div id="ce">
            <f:for each="{v:content.resources.fal(field: 'settings.images')}" as="image">
                <f:render section="Item" arguments="{_all}" />
            </f:for>
        </div>
    </f:section>
</div>
```

**Comment by NamelessCoder** [comment]
Avoided by forced HTML formatting.
