### ISSUE TITLE
[FEATURE] Provide by default the ability to fluidcontent to be able to read content.settings from fluidcontent_core

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/fluidcontent_core#176]
**As developer** I want to be able to use the settings relatives content.settings.container or content.settings.header from mycustomcontent in myproviderextension because I'm able to see

**Headlines:**
![headlines](https://cloud.githubusercontent.com/assets/2902073/9008232/18e5ecb2-3799-11e5-9879-a2419b1191c8.png)

**Apparence tab:**
![apparence](https://cloud.githubusercontent.com/assets/2902073/9008234/20517d22-3799-11e5-8c13-23e12de813bd.png)

**Comment by konstantin83** [comment]
I have made a custom and quick the way to solve this problem:
```HTML
<flux:form.data table="tt_content" field="content_options" uid="{record.uid}" as="content">
  <v:tag name="h{content.settings.header.type -> v:or(alternative: record.header_layout) -> v:or(alternative: settings.header.type)}" class="{content.settings.header.className}" hideIfEmpty="{content.settings.header.hideIfEmpty -> v:or(alternative: 1)}">
    {record.header -> f:format.raw()}
  </v:tag>
</flux:form.data>
```

In Typo3 headlines with it's custom layout are now fully rendered with FLUIDCONTENT_CORE

**Comment by NamelessCoder** [comment]
Note: the linked patch provides these values BUT please be aware that the addressing scope is different: `settings.content` now contains what was in `content` - so you will be seeing `settings.content.settings`! FluidcontentCore templates are not yet updated to reflect this fact.
