### ISSUE TITLE
plugin "news" doesnt display with fluidcontent_core

### ISSUE THREAD

**Issue by farconada** [FluidTYPO3/fluidcontent_core#185]
plugins news displays nothing in frontend with fluidcontent_core. with csc_ works great

**Comment by konstantin83** [comment]
Check if there is a file named AdditionalConfiguration.php in typo3conf/.
Somehow it's not installed often...

**Comment by xf-** [comment]
Hey,

normally the issue is like @konstantin83 wrote AddionalCOnfigruiatiuon. We rewrote the process to ensure the lines are present and a PR to install it on installation is on its way.
