### ISSUE TITLE
Missing image width height in Image CE

### ISSUE THREAD

**Issue by konstantin83** [FluidTYPO3/fluidcontent_core#187]
Typo3 7.4
Fluidcontent_core 1.2.0
fluidpages 3.3.1
fluidcontent 4.3.1

1. Missing image width height in Image CE
![2015-08-19 14 55 33](https://cloud.githubusercontent.com/assets/13274062/9355481/66ce9472-4682-11e5-80fc-bffd08364573.png)
2. Preview of Image CE in backend is crazy - it creates "+ content" buttons somehow after every listed (why?) image caption.
![2015-08-19 14 52 30](https://cloud.githubusercontent.com/assets/13274062/9355482/670669f6-4682-11e5-8b10-8a750c8ec98a.png)

**Comment by NamelessCoder** [comment]
Hi Konstantin,

This is expected behavior. With the checkbox you explicitly instruct Flux to create a nested content area for each image. You can disable the checkbox or override the template and make IRRE or other methods to select content elements to use as captions. That's the same way you would use to add width and height selectors (but we recommend you use something like CSS class names in a select to use rules instead of direct numbers to define image sizes).

**Comment by konstantin83** [comment]
Hi, thanks for the reply.

In fact, I guess, that setting image width and height would be more preferable, because some uploaded images can be too large, and by setting max width and height you tell Typo3 to make them smaller. Using CSS instead will load them as they are and just decrease it’s rendering to a smaller image, which is not too good for page load time.

> 19 авг. 2015 г., в 21:31, Claus Due <notifications@github.com> написал(а):
> 
> Hi Konstantin,
> 
> This is expected behavior. With the checkbox you explicitly instruct Flux to create a nested content area for each image. You can disable the checkbox or override the template and make IRRE or other methods to select content elements to use as captions. That's the same way you would use to add width and height selectors (but we recommend you use something like CSS class names in a select to use rules instead of direct numbers to define image sizes).
> 
> —
> Reply to this email directly or view it on GitHub.
> 

С уважением,
Константин Салахутдинов

**Comment by NamelessCoder** [comment]
Hi Konstantin,

> Using CSS instead will load them as they are and just decrease it’s rendering to a smaller image, which is not too good for page load time.

That definitely depends on how you implement your assets. You can let the editor select from a predefined list of named sizes that you then translate to width and height - and you can for example define these sets of dimensions using TS.

It is our view that image sizes in pixels as a decision should never be left to the content editor. Its a fine setting for admins or people knowing exactly what they're doing, but it is much less flexible and prone to problems than any other approach - for obvious reasons.
