### ISSUE TITLE
Sysext "form" in Typo3 7.4 causes whitescreen in FE

### ISSUE THREAD

**Issue by konstantin83** [FluidTYPO3/fluidcontent_core#188]
Sysext "form" in Typo3 7.4 causes whitescreen in FE when inserted to a page, while using fluidcontent_core, fluidcontent, fluidpages.

**Comment by NamelessCoder** [comment]
We need the proper error message - you can for example enable "development context" in the install tool.

**Comment by konstantin83** [comment]
Fatal error: Call to a member function render() on a non-object in /home/k/konstantin/typo3_src-7.4.0/typo3/sysext/form/Classes/Controller/FormController.php on line 92

Actually I opened issue on typo3 forge (https://forge.typo3.org/issues/69195) and found out there that fresh installation of Typo3 7.4 somehow still uses old mailform content element, which can only be rendered with ext:compatibility6. Don't know why it is like that. If this content element is old, then why is it used in fresh 7.4 installation?

**Comment by NamelessCoder** [comment]
> If this content element is old, then why is it used in fresh 7.4 installation?

I think someone just forgot to either remove it, move it's registrations to `compatibility6` or completely revamp it. In any case: thanks for reporting to the TYPO3 core bug tracker! That's what I was going to suggest next and it's great you already did it ;)

**Comment by konstantin83** [comment]
Then only thing that's left for forms in modern typo3 versions is powermail?

**Comment by NamelessCoder** [comment]
There are quite a few tailored solutions out there but if you need one that's flexible (e.g. not a specific contact form, subscription form, comment or whatever) then the only good alternative I know of is, yes, powermail. I expect the native form element to be updated in 7.5 or they provide an alternative with an upgrade path.

**Comment by konstantin83** [comment]
Ok then. Thanks for you replies ))
