### ISSUE TITLE
In CE Div the header is not ignored

### ISSUE THREAD

**Issue by MoppieMop** [FluidTYPO3/fluidcontent_core#191]
In the Content Element "Div" there is the field "Name (not visible in frontend)" but the field IS visible. I think it is because the div-template does not use the NoHeader-Layout.

**Comment by jmverges** [comment]
Hi @MoppieMop would you like to create a PR for this one? you can follow our contribution guide here: https://fluidtypo3.org/documentation/contributing/contribution-guide.html

**Comment by NamelessCoder** [comment]
Fixed
