### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by xf-** [FluidTYPO3/fluidcontent_core#194]
Problem:
Add a new image and choose a svg and set no responsive image. The size will be -1x-1 in FE.

Workaround:
Set appearance a responsive image.

Info:
Preview works fine

I think this is not a good behavior. SVG have a size, for example be px or % in first line.

**Comment by NamelessCoder** [comment]
You had a fix for this one right, @xf-? I lost the gist link... could you throw that in a PR for us? :)

**Comment by xf-** [comment]
i had more like a workaround. Records provide file-ending and i added a simple <f:if>

**Comment by NamelessCoder** [comment]
Partially solved - can be worked around with custom templates - will become the responsibility of `fluid_styled_content` when we convert `fluidcontent_core` to a Flux integration for that extension. Taking the liberty of closing this one.
