### ISSUE TITLE
Insert Record (shortcut) with custom fluid_content CE's

### ISSUE THREAD

**Issue by christophmellauner** [FluidTYPO3/fluidcontent_core#196]
Hey i don't know if its a bug or i am making a mistake, but i can't "insert Record" on a custom CE i made with fluid_content.

In the ShortcutAction ind the CoreController $index is the UId of my CE.
https://github.com/FluidTYPO3/fluidcontent_core/blob/development/Classes/Controller/CoreContentController.php#L167
But it returns false.

Shouldn't there be an option to check if its an valid CE's UId?

Greets Christoph

**Comment by konstantin83** [comment]
can you provide screenshot to be more specific?

**Comment by jmverges** [comment]
Hi @christophmellauner ,

I had the same problem the last week but this should be solved now with TYPO3 master (7LTS) and development branches of FluidTYPO3.

I'm going to close this issue but if you are able to reproduce the problem again feel free to reopen it.
