### ISSUE TITLE
Wrapper 

### ISSUE THREAD

**Issue by mitrovicsinisaa** [FluidTYPO3/fluidcontent_core#199]
Hello,
Is it possible to add wrapper div with class defined in FlexForm of Fluid Styled Content Element?
Something like Frames in CSS_styled_content?

Best regards,
Sinisa Mitrovic

**Comment by NamelessCoder** [comment]
Hi Sinisa,

Sure thing - the easiest way would be to use the "container" sheet that fluidcontent_core already provides, combined with a Layout that uses `v:tag` to make the wrapper node:

https://github.com/FluidTYPO3/fluidcontent_core/blob/development/Resources/Private/Templates/CoreContent/Bullets.html#L10

https://github.com/FluidTYPO3/fluidcontent_core/blob/development/Resources/Private/Layouts/Default.html#L9
