### ISSUE TITLE
Some language labels does not appear under TYPO3 6.2

### ISSUE THREAD

**Issue by rabe69** [FluidTYPO3/fluidcontent_core#201]
Some language labels assigned in Configuration/TCA/Overrides/tt_content.php do not exists under TYPO3 6.2. Due to this fact, some tabs and palette titles are empty in backend.

Affected are:
```
LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance
LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.frames
```
To preserve backward compatibility to 6.2 a condition should be added.

The corresponding labels under 6.2 are:
```
LLL:EXT:cms/locallang_ttc.xlf:tabs.appearance
LLL:EXT:cms/locallang_ttc.xlf:palette.frames
```

**Comment by NamelessCoder** [comment]
Next release raises minimum required TYPO3 version to 7.6 which should have labels in all the right places ;)
