### ISSUE TITLE
[TYPO3 7] Conflict with SYSEXT: fluid_styles_content

### ISSUE THREAD

**Issue by MarvinRudolph** [FluidTYPO3/fluidcontent_core#203]
It seems that fluidcontent_core conflicts with the fluid_styled_content system extension.
F.E. he new textmedia content element only shows the headline and not it's content (image, video & text).

**Comment by xf-** [comment]
No real issue - it is basically the same thing.

**Comment by MarvinRudolph** [comment]
Yea but it conflicts and you won't get the correct output.

**Comment by xf-** [comment]
Of course it will conflict, handles the same elements.

**Comment by MarvinRudolph** [comment]
I think it should be listed next to "css_styled_content" in "conflicts" of $EM_CONF.
