### ISSUE TITLE
[Question] Possibilty of setting a max image width? Perhaps globally?

### ISSUE THREAD

**Issue by haraldkrischner** [FluidTYPO3/fluidcontent_core#208]
Hey everybody,
I am looking for a possibility to restrict the maximum image size of an image element anywhere on my site. Alternatively I could overlay the image renderer template.
In css_styled_content there was this `styles.content.imgtext.maxW = 1920` or `tt_content.image.20.maxW = 1920` setting, but I don't see anything comparable in the Fluidtypo3 elements.
Somewhere I found mentioned something like `<v:content.render column="1" loadRegister="{maxImageWidth: 400}"/>`, but this simply didn't change anything.
Thanks everyone

**Comment by NamelessCoder** [comment]
Hi Harald,

In `fluidcontent_core` the image dimensions are not provided in the template (our approach is that this is not a decision to be made by the content editor). However, you can implement this in custom templates by using loadRegister if you wish:

1. Specify the maximum with in standard load register using any method you prefer.
2. Use https://fluidtypo3.org/viewhelpers/vhs/master/Variable/Register/GetViewHelper.html in your custom version of the `image` content type (use template replacement, versions or variants to achieve this - see README.md).

But perhaps you should consider a more static solution, for example delivering the maximum image width as a TypoScript constant. It's a suggestion at least :)
