### ISSUE TITLE
fluidcontent_core or fluid styled content

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/fluidcontent_core#218]
Hi,
when using flux, fluidpages, fluidcontent etc. in TYPO3 7.6

must i automatically use fluidcontent_core or can i also choose fluid styled content?
or even css styled content?

best regards
blueamerican

**Comment by NamelessCoder** [comment]
You can use any of the above combined with Flux. If you use `fluidcontent_core` you get some additional features like being able to change form fields via overridden templates, but `fluid_styled_content` also works (just without the Flux integration). Same for `css_styled_content`.

At some point we will be deprecating `fluidcontent_core` in favor of a Flux integration for `fluid_styled_content` but there are no certain plans for that yet.
