### ISSUE TITLE
Extending bullets_type, imageorient, uploads_type, etc. not possible

### ISSUE THREAD

**Issue by phifa** [FluidTYPO3/fluidcontent_core#219]
I want to extend the bullets select field. It shows up, I can select it, but no output. Here is what I have so far:

PageTS (works):
```
TCEFORM.tt_content {
    bullets_type {
        addItems {
            10 = Un-bulleted List
        }
    }
}
```

FSC Bullets.html (no output):
```
<f:case value="10">
    <ul class="no-bullet">
        <f:for each="{bullets}" as="bullet">
            <li>{bullet}</li>
        </f:for>
    </ul>
</f:case>
```

Same behaviour for `TCEFORM.tt_content.imageorient`, `TCEFORM.tt_content.uploads_type`, etc. 

Regarding bullets, it looks like Only values 0, 1 and 2 are processed: 
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid_styled_content/Configuration/TypoScript/Static/setup.txt#L22-L55

**Comment by NamelessCoder** [comment]
Hi @phifa - please report this one to the TYPO3 core bug tracker. The report concerns the **system** extension `fluid_styled_content` and you've reached the bug tracker for the **community** extension `fluidcontent_core`. Indeed, the names are not ideal, but I guess the TYPO3 core had to pick *some* name for their replacement for CSS Styled Content ;)
