### ISSUE TITLE
Peer review core templates and settings

### ISSUE THREAD

**Issue by danilobuerger** [FluidTYPO3/fluidcontent_core#35]
Dear `fluidcontent_core` users,

We are doing an open review of the options and templates which we will ship with the first official release of `fluidcontent_core`. In order to have the best possible starting point we ask for your suggestions. Below you will see a list of topics which are being decided by us - if you have input on any of the so far uncompleted topics please give us your thoughts in this issue's comments.

Before you do:

In order to avoid shipping a bloated and/or too generic set of templates and options we ask that you observe the following guidelines before chipping in:

1. The `Textpic` element is left out intentionally and will not be added. You can read a more detailed explanation of why this is so, at https://github.com/FluidTYPO3/fluidcontent_core#special-note-about-the-textpic-text-with-images-content-type.
2. We are not trying to reinvent the core elements' options - we are trying to define a set of shipped options which _are relevant to everyone_. One of the major points of `fluidcontent_core` is the ease with which you can change **every** aspect of the attributes added by `fluidcontent_core` - so we actively try to avoid adding any attributes or renderings which are not universally useful (or at the very least serve as the perfect starting point for customisation).
3. We will not add any new content types - no column-type elements for example. Such elements are the sole responsibility of the integrator or developer, and should be created using `fluidcontent` rather than added as new core element types. _We may choose to add such elements in the future but for this first version, we choose not to_.

## Topics of review

- [x] Finish Menu.html
- [x] Add ability to Table.html to make first row ``th`` elements
- [x] Gather wishes for shipped TypoScript settings
  - [x] Header settings
  - [x] Container settings
  - [x] Tag names
  - [x] Shipped CSS class selection options
  - [x] Image settings (globals and defaults)
- [x] Gather wishes for Flux form settings
  - [x] Removals (redundant, exotic settings)
  - [x] Additions (must be universally useful)
  - [x] Changes (existing fields' types, labels, names etc)

**Comment by xf-** [comment]
Remove Media.
Media is fluidcontent, because scaled videos, different formats are hard to provide, best you use your optimal solution. From simple <video> up to a service like vimeo or youtube.

-> Removed media from list

**Comment by xf-** [comment]
This should be the last open part from menu:
https://github.com/FluidTYPO3/fluidcontent_core/issues/132

**Comment by xf-** [comment]
Was the last issue.
Works in daily usage.
