### ISSUE TITLE
felogin does not work with fluid content_core

### ISSUE THREAD

**Issue by Crewcut** [FluidTYPO3/fluidcontent_core#97]
TYPO3 CMS 6.2.5, all FluidTYPO3 ext up to date (fluidcontent_core from TER).

When installed fluidcontent_core, felogin box disappeared on FE. Removed fluid content_core and re-installed css_styled_content. felogin box reappeared.

Bug?

Regards,
Crewcut

**Comment by NamelessCoder** [comment]
A replacement login extension is being written as part of the TYPO3 core and is expected to be included in 7.2. It will use Extbase and Fluid, and will not depend on CSC (nor FCC) - it should be completely compatible with both extensions. Until then, I'm afraid the best/only option here is to create a custom template for this and use the same field names as `felogin` would. TYPO3 will handle these posted values even when you don't have a custom controller to catch them.

**Comment by renemaas** [comment]
Sry that I am commenting to an old thread, but I did not find any other content concering this topic.

Is the replacement extension available now?

**Comment by Crewcut** [comment]
I have no idea, as i have migrated to Neos.

Regards,

Kim

2016-06-15 14:36 GMT+02:00 René Maas <notifications@github.com>:
